package com.example.demo.mock;

import com.example.demo.post.domain.Post;
import com.example.demo.post.service.port.PostRepository;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.Optional;

public class FakePostRepository implements PostRepository {

    private Long autoGeneratedId = 0L;
    private final List<Post> data = new ArrayList<>();

    @Override
    public Post save(Post post) {
        if (post.id() == null || post.id() == 0) {
            Post newPost = Post.builder()
                    .id(++autoGeneratedId)
                    .content(post.content())
                    .createdAt(post.createdAt())
                    .modifiedAt(post.modifiedAt())
                    .writer(post.writer())
                    .build();
            data.add(newPost);
            return newPost;
        } else {
            data.removeIf(item -> Objects.equals(item.id(), post.id()));
            data.add(post);
            return post;
        }
    }

    @Override
    public Optional<Post> findById(long id) {
        return data.stream()
                .filter(item -> item.id().equals(id))
                .findAny();
    }
}
